# Generated by Django 3.2.6 on 2021-08-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaffeApp', '0007_auto_20210828_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='sauce',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
