# Generated by Django 3.2.6 on 2021-08-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaffeApp', '0008_sauce_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauce',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
