# Generated by Django 3.2.6 on 2021-08-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaffeApp', '0009_alter_sauce_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sauce',
            field=models.ManyToManyField(blank=True, to='CaffeApp.Sauce'),
        ),
    ]
