# Generated by Django 3.2.6 on 2021-09-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CaffeApp', '0010_alter_product_sauce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sauce',
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
    ]
